#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ffi
Version  : 1.9.10
Release  : 6
URL      : https://rubygems.org/downloads/ffi-1.9.10.gem
Source0  : https://rubygems.org/downloads/ffi-1.9.10.gem
Summary  : Library supporting Foreign Function Interfaces
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: rubygem-ffi-lib
BuildRequires : libffi-dev
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
Status
======
libffi-3.0.10 was released on August 23, 2011. Check the libffi web
page for updates: <URL:http://sourceware.org/libffi/>.

%package dev
Summary: dev components for the rubygem-ffi package.
Group: Development
Requires: rubygem-ffi-lib
Provides: rubygem-ffi-devel

%description dev
dev components for the rubygem-ffi package.


%package lib
Summary: lib components for the rubygem-ffi package.
Group: Libraries

%description lib
lib components for the rubygem-ffi package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ffi-1.9.10
gem spec %{SOURCE0} -l --ruby > rubygem-ffi.gemspec

%build
gem build rubygem-ffi.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ffi-1.9.10.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ffi-1.9.10
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ffi-1.9.10.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10/gem_make.out
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10/mkmf.log
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/README.md
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/AbstractMemory.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/AbstractMemory.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/AbstractMemory.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ArrayType.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ArrayType.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ArrayType.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Buffer.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Buffer.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Call.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Call.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Call.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ClosurePool.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ClosurePool.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ClosurePool.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/DataConverter.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/DataConverter.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/DynamicLibrary.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/DynamicLibrary.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/DynamicLibrary.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Function.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Function.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Function.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/FunctionInfo.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/FunctionInfo.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/LastError.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/LastError.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/LastError.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/LongDouble.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/LongDouble.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/LongDouble.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MappedType.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MappedType.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MappedType.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MemoryPointer.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MemoryPointer.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MemoryPointer.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MethodHandle.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MethodHandle.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/MethodHandle.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Platform.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Platform.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Platform.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Pointer.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Pointer.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Pointer.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Struct.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Struct.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Struct.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/StructByReference.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/StructByReference.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/StructByReference.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/StructByValue.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/StructByValue.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/StructByValue.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/StructLayout.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/StructLayout.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Thread.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Thread.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Thread.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Type.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Type.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Type.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Types.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Types.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Types.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Variadic.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/Variadic.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/compat.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/extconf.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ffi.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi.bsd.mk
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi.darwin.mk
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi.gnu.mk
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi.mk
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi.vc.mk
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi.vc64.mk
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/ChangeLog
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/ChangeLog.libffi
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/ChangeLog.libgcj
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/ChangeLog.v1
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/Makefile.am
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/Makefile.in
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/Makefile.vc
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/Makefile.vc64
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/README
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/acinclude.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/aclocal.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/build-ios.sh
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/compile
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/config.guess
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/config.sub
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/configure
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/configure.ac
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/configure.host
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/depcomp
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/doc/libffi.info
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/doc/libffi.texi
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/doc/stamp-vti
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/doc/version.texi
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/fficonfig.h.in
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/fficonfig.hw
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/include/Makefile.am
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/include/Makefile.in
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/include/ffi.h.in
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/include/ffi.h.vc
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/include/ffi.h.vc64
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/install-sh
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/libffi.pc.in
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/libtool-version
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/ltmain.sh
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ax_cc_maxopt.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ax_cflags_warn_all.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ax_check_compiler_flags.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ax_compiler_vendor.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ax_configure_args.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ax_enable_builddir.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ax_gcc_archflag.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ax_gcc_x86_cpuid.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/libtool.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ltoptions.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ltsugar.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/ltversion.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/m4/lt~obsolete.m4
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/man/Makefile.am
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/man/Makefile.in
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/man/ffi.3
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/man/ffi_call.3
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/man/ffi_prep_cif.3
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/mdate-sh
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/missing
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/msvcc.sh
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/alpha/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/alpha/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/alpha/osf.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/arm/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/arm/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/arm/gentramp.sh
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/arm/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/arm/trampoline.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/avr32/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/avr32/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/avr32/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/closures.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/cris/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/cris/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/cris/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/debug.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/dlmalloc.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/frv/eabi.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/frv/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/frv/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/ia64/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/ia64/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/ia64/ia64_flags.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/ia64/unix.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/java_raw_api.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/m32r/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/m32r/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/m32r/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/m68k/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/m68k/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/m68k/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/mips/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/mips/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/mips/n32.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/mips/o32.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/moxie/eabi.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/moxie/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/pa/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/pa/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/pa/hpux32.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/pa/linux.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/aix.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/aix_closure.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/asm.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/darwin.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/darwin_closure.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/ffi_darwin.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/linux64.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/linux64_closure.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/ppc_closure.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/powerpc/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/prep_cif.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/raw_api.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/s390/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/s390/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/s390/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sh/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sh/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sh/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sh64/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sh64/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sh64/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sparc/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sparc/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sparc/v8.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/sparc/v9.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/types.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/darwin.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/darwin64.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/ffi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/ffi64.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/ffitarget.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/freebsd.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/sysv.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/unix64.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/win32.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/src/x86/win64.S
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/Makefile.am
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/Makefile.in
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/config/default.exp
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/lib/libffi-dg.exp
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/lib/libffi.exp
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/lib/target-libpath.exp
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/lib/wrapper.exp
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/call.exp
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_fn0.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_fn1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_fn2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_fn3.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_fn4.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_fn5.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_fn6.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_loc_fn0.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/closure_stdcall.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_12byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_16byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_18byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_19byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_1_1byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_20byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_20byte1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_24byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_2byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_3_1byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_3byte1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_3byte2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_4_1byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_4byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_5_1_byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_5byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_64byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_6_1_byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_6byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_7_1_byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_7byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_8byte.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_9byte1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_9byte2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_double.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_float.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_longdouble.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_longdouble_split.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_longdouble_split2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_pointer.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_sint16.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_sint32.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_sint64.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_uint16.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_uint32.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_align_uint64.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_dbls_struct.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_double.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_double_va.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_float.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_longdouble.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_longdouble_va.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_multi_schar.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_multi_sshort.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_multi_sshortchar.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_multi_uchar.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_multi_ushort.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_multi_ushortchar.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_pointer.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_pointer_stack.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_schar.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_sint.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_sshort.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_uchar.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_uint.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_ulonglong.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/cls_ushort.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/err_bad_abi.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/err_bad_typedef.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/ffitest.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/float.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/float1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/float2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/float3.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/float4.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/huge_struct.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/many.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/many_win32.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/negint.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct10.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct3.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct4.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct5.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct6.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct7.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct8.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/nested_struct9.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/problem1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/promotion.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/pyobjc-tc.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_dbl.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_dbl1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_dbl2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_fl.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_fl1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_fl2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_fl3.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_ldl.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_ll.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_ll1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_sc.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_sl.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_uc.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/return_ul.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/stret_large.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/stret_large2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/stret_medium.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/stret_medium2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/strlen.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/strlen_win32.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct1.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct2.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct3.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct4.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct5.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct6.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct7.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct8.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/struct9.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.call/testclosure.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.special/ffitestcxx.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.special/special.exp
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.special/unwindtest.cc
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/testsuite/libffi.special/unwindtest_ffi_call.cc
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/texinfo.tex
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/rbffi.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/rbffi_endian.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/win32/stdbool.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/win32/stdint.h
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ffi.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/gen/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/autopointer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/buffer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/callback.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/enum.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/errno.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/ffi.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/io.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/managedstruct.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/memorypointer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/aarch64-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/arm-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-cygwin/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-darwin/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-freebsd/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-gnu/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-netbsd/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-openbsd/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-solaris/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/i386-windows/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/ia64-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/mips-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/mips64el-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/mipsel-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/powerpc-aix/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/powerpc-darwin/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/powerpc-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/powerpc64-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/s390-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/s390x-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/sparc-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/sparc-solaris/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/sparcv9-solaris/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/x86_64-cygwin/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/x86_64-darwin/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/x86_64-freebsd/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/x86_64-linux/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/x86_64-netbsd/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/x86_64-openbsd/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/x86_64-solaris/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/platform/x86_64-windows/types.conf
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/pointer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/struct.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/struct_layout_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/tools/const_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/tools/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/tools/generator_task.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/tools/struct_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/tools/types_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/types.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/union.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/variadic.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/Benchmark.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/BoolTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/BufferTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/ClosureTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/EnumTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/FunctionTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/GNUmakefile
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/GlobalVariable.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/LastErrorTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/NumberTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/PointerTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/ReferenceTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/StringTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/StructTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/UnionTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/libtest/VariadicTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/LICENSE.SPECS
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/async_callback_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/bool_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/buffer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/callback_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/custom_param_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/custom_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/dup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/enum_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/errno_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/ffi_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/Benchmark.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/Benchmark.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/BoolTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/BoolTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/BufferTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/BufferTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/ClosureTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/ClosureTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/EnumTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/EnumTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/FunctionTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/FunctionTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/GNUmakefile
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/GlobalVariable.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/GlobalVariable.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/LastErrorTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/LastErrorTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/NumberTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/NumberTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/PointerTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/PointerTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/ReferenceTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/ReferenceTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/StringTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/StringTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/StructTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/StructTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/UnionTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/UnionTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/VariadicTest.c
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/VariadicTest.o
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/classes.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/function_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/io_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/library_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/long_double.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/managed_struct_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/memorypointer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/number_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/platform_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/pointer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/rbx/attach_function_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/rbx/memory_pointer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/rbx/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/rbx/struct_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/strptr_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/struct_by_ref_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/struct_callback_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/struct_initialize_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/struct_packed_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/struct_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/typedef_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/union_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/variadic_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/specifications/ffi-1.9.10.gemspec

%files dev
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/libffi/include/ffi_common.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10/ffi_c.so
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c/ffi_c.so
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi_c.so
/usr/lib64/ruby/gems/2.3.0/gems/ffi-1.9.10/spec/ffi/fixtures/libtest.so
